import pyautogui
import time
print(" _  ___           _                 _       _     ")
print("| |/ (_)_ __   __| | __ _  ___ __ _| |_ ___| |__  ")
print("| ' /| | '_ \ / _` |/ _` |/ __/ _` | __/ __| '_ \ ")
print("| . \| | | | | (_| | (_| | (_| (_| | || (__| | | |")
print("|_|\_\_|_| |_|\__,_|\__,_|\___\__,_|\__\___|_| |_|")
print("  ")
print("  ")
print("  ")
print("  ")
print("  ")
print("Please Choose what you want to spam (you will have ten seconds to go to the destination of spam")
print("A] full song                                 B] fastest verse ")
a = str(input("Enter the digit :  ") 
if a = "A":
        print(10)
        time.sleep(1)
        print(9)
        time.sleep(1)
        print(8)
        time.sleep(1)
        print(7)
        time.sleep(1)
        print(6)
        time.sleep(1)
        print(5)
        time.sleep(1)
        print(4)
        time.sleep(1)
        print(3)
        time.sleep(1)
        print(2)
        time.sleep(1)
        print(1)
        time.sleep(1)
        print(0)
        b = open("song", 'r')
        for c in b:
                pyautogui.typewrite(c)
                pyautogui.press("enter")
else :
        print(10)
        time.sleep(1)
        print(9)
        time.sleep(1)
        print(8)
        time.sleep(1)
        print(7)
        time.sleep(1)
        print(6)
        time.sleep(1)
        print(5)
        time.sleep(1)
        print(4)
        time.sleep(1)
        print(3)
        time.sleep(1)
        print(2)
        time.sleep(1)
        print(1)
        time.sleep(1)
        print(0)
        d = open("verse", 'r')
        for e in d:
                pyautogui.typewrite(e)
                pyautogui.press("enter")
